### ISSUE TITLE
License Inconsistency

### ISSUE THREAD

**Issue by kory33** [Kory33/UpdateNotificationPlugin#5]
As this project makes use of Bukkit, which is released under GPLv3, this project also is required to adopt GPLv3.
As most part of the project, including @4oi's and @Bnana877's contribution, has already been licensed by MIT License, I might need permission to re-license this library as a GPLv3 project.

**Comment by 4oi** [comment]
ok :)

**Comment by Bnana877** [comment]
OK

**Comment by kory33** [comment]
Closed. Thank you for agreeing and understanding :)
